services:
  - type: web
    name: hulet-fish
    env: node
    root: "Hulet Fish"
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/v1/health
